# Generated by Django 5.1.4 on 2024-12-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_subtask_due_date_alter_subtask_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='task',
        ),
    ]
