# Generated by Django 5.1.4 on 2024-12-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_list_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='tasks',
            field=models.ManyToManyField(to='main_app.task'),
        ),
    ]
