# Generated by Django 5.1.4 on 2024-12-12 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_list_tasks_task_list_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.list'),
        ),
    ]
