# Generated by Django 5.1.4 on 2024-12-14 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_task_list_key_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Due Date'),
        ),
    ]
