# Generated by Django 5.1.4 on 2024-12-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_profile_zipcode_alter_subtask_due_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
